//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public int AchievementID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> AwardId { get; set; }
        public Nullable<System.DateTime> AchieveDate { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual Member Member { get; set; }
    }
}
