//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int FineID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> OrganizationLevelID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual OrganizationLevel OrganizationLevel { get; set; }
    }
}
