//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MemberMSEntities : DbContext
    {
        public MemberMSEntities()
            : base("name=MemberMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<DesignationType> DesignationTypes { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<DonationsType> DonationsTypes { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Fine> Fines { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MembershipFee> MembershipFees { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<OrganizationLevel> OrganizationLevels { get; set; }
        public virtual DbSet<OrganizationSchema> OrganizationSchemas { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
