//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationSchema
    {
        public int SchemaObjectID { get; set; }
        public string SchemaObjectName { get; set; }
        public string SchemaObjectValue { get; set; }
        public string Remarks { get; set; }
    }
}
